#pragma once


// has to start counting at 1, return id 0 from callback results in remaining in same menu
typedef enum{
    M_MAIN = 0x01,
    M_PLAY,
    M_SLOT,
    M_SLOT_TYPESELECT,
    M_SLOT_FILEBROWSER,
    M_SLOT_DECODING,
    M_SLOT_USER,
    M_BROWSE,
    M_BROWSE_TAG,
    M_BROWSE_TAG_RESULTS,
    M_BROWSE_SEARCH,
    M_BROWSE_ID,
    M_BROWSE_ID_RESULT,
    M_BROWSE_USER,
    M_MORE,
    M_MACHINE_SEL,
    M_LOOPER_LIVE,
    M_LOOPER_SETUP,
    M_SLICER_LIVE,
    M_SLICER_SETUP,
    M_SLICER_LOAD,
    M_SLICER_SENS,
    M_GRAN_LIVE,
    M_GRAN_SETUP,
    M_GRAN_LOAD,
    M_GLITCH_LIVE,
    M_GLITCH_SETUP,
    M_DRUM_LIVE,
    M_DRUM_PADS,
    M_DRUM_LOAD,
    M_DRUM_SETUP,
    M_FS_LIVE,
    M_DECK_LIVE,
    M_DECK_SETUP,
    M_DECK_LOAD,
    M_TRACKER_LIVE,
    M_TRACKER_SETUP,
    M_TRACKER_LOAD,
    M_S3_LIVE,
    M_S3_SETUP,
    M_S3_LOAD,
    M_S3_REC,
    M_DD_LIVE,
    M_DD_SETUP,
    M_DD_LOAD,
    M_DD_CV,
    M_RADIO_LIVE,
    M_RADIO_SETUP,
    M_SYNTH_LIVE,
    M_SYNTH_SETUP,
    M_SYNTH_LOAD,
    M_SYNTH_MATRIX,
    M_SYNTH_PATCH,
    M_ISMP_LIVE,
    M_ISMP_SETUP,
    M_ISMP_LOAD,
    M_ISMP_MATRIX,
    M_ISMP_PATCH,
    M_TAPE_MAIN,
    M_TAPE_SETUP,
    M_TAPE_LOAD,
    M_EDITOR_LIVE,
    M_EDITOR_SETUP,
    M_STUB_HOME,
    M_SETTINGS,
    M_SETTINGS_INPUT,
    M_ABOUT,
    M_VOICE,
    M_VOICE0,
    M_VOICE1,
    M_EXTERNAL_IN,
    M_EFFECTS,
    M_CV_MATRIX,
    M_DELAY,
    M_RECORDING,
    M_REVERB,
    M_FILTER,
    M_ADSR,
    M_PLAYMODE,
    M_PRESET,
    M_PRESET_P,
    M_PRESET_B,
    M_PRESET_LOAD,
    M_PRESET_STORE,
    M_PRESET_NEW,
    M_PRESET_RESET,
    M_PRESET_DELETE,
    M_PRESET_BANK_LOAD,
    M_PRESET_BANK_NEW,
    M_PRESET_BANK_DELETE
} menu_ids_t;

typedef enum{
    SID_TRIG_TYPE,
    SID_VOLUME,
    SID_PAN,
    SID_PITCH,
    SID_PITCH_CV_ACTIVE,
    SID_PBSPEED,
    SID_DIST_ACTIVE,
    SID_DIST,
    SID_DELAY_SEND,
    SID_DELAY_ACTIVE, 
    SID_DELAY_MODE,
    SID_DELAY_TIME,
    SID_DELAY_PAN,
    SID_DELAY_FEEDBACK,
    SID_DELAY_VOLUME,
    SID_FILTER_ACTIVE,
    SID_BASE,
    SID_WIDTH,
    SID_Q,
    SID_ATTACK,
    SID_DECAY,
    SID_SUSTAIN,
    SID_RELEASE,
    SID_ENV_ACTIVE,
    SID_MODE,
    SID_START,
    SID_LSTART,
    SID_LEND,
    SID_LPOSITION,
    SID_EXTIN_ACTIVE,
    SID_EXTIN_VOLUME,
    SID_EXTIN_PAN,
    SID_EXTIN_DELAY_SEND, 
    SID_WIFI_SSID,
    SID_WIFI_PASSWD,
    SID_APIKEY,
    SID_TIMEZONE,
    SID_REMOTE,
    SID_LISTEN,        // beatlisten mode (System Settings row)
    SID_CLKOUT,        // beatlisten clock-out channel
    SID_BOUNCE         // record the active machine's OUTPUT bus (press to toggle)
} submenu_ids_t;

typedef enum{
    PRINT_ALL = 0xFF,
    PRINT_FAST,
    PRINT_CLEAR,
    PRINT_UPPER,
    PRINT_NORM
} print_ids_t;

typedef struct{
    int x;
    int y; 
}p2d_t;
